/**
 * Docs registry — single source of truth for the docs site nav + sitemap.
 *
 * Every entry maps a slug (URL segment under `/docs/...`) to:
 *   - the on-disk markdown source under `apps/web/content/docs`
 *   - the section it belongs to in the sidebar
 *   - the human-readable title used in nav, search, and OG images
 *   - an optional `auto` flag (true = generated MDX, do not migrate)
 *
 * The registry is intentionally hand-curated rather than discovered at
 * runtime: it lets us order the sidebar without bolting on filename
 * prefixes (`01-quickstart.md`), and it lets the build-time API-ref
 * generator append rows without renaming files.
 *
 * LLM-agnostic: no doc page is provider-named. The local-models guide
 * does mention runtime adapter identifiers (Ollama, vLLM, llama.cpp,
 * MLX) — those are runtime backends, not LLM providers, and the page
 * is explicitly about them.
 */

export interface DocSection {
  /** URL-safe key, used as the path prefix segment when non-root. */
  readonly key: DocSectionKey;
  /** Sidebar heading. */
  readonly label: string;
  /** True for the implicit "" section that mounts at `/docs` directly. */
  readonly root?: boolean;
}

export type DocSectionKey = 'overview' | 'concepts' | 'guides' | 'api' | 'sdks' | 'reference';

export interface DocPage {
  /** URL slug under /docs (no leading slash, e.g. "concepts/privacy-tier"). */
  readonly slug: string;
  /** Section group in the sidebar. */
  readonly section: DocSectionKey;
  /** Human-readable title; rendered as <h1> and OG image text. */
  readonly title: string;
  /** Short summary, used in the docs landing TOC + search index. */
  readonly summary: string;
  /**
   * Source location relative to `apps/web/content/docs`. When omitted,
   * the slug itself (with a `.md` extension) is assumed.
   */
  readonly source?: string;
  /** True when the file is regenerated by `generate-api-docs.ts`. */
  readonly generated?: boolean;
}

export const DOC_SECTIONS: ReadonlyArray<DocSection> = [
  { key: 'overview', label: 'Overview', root: true },
  { key: 'concepts', label: 'Concepts' },
  { key: 'guides', label: 'Guides' },
  { key: 'api', label: 'API reference' },
  { key: 'sdks', label: 'SDKs' },
  { key: 'reference', label: 'Reference' },
];

/**
 * Hand-curated nav. New pages are appended to the end of their
 * section. The order here IS the sidebar order.
 */
export const STATIC_DOC_PAGES: ReadonlyArray<DocPage> = [
  {
    slug: '',
    section: 'overview',
    title: 'Documentation',
    summary: 'ALDO AI documentation: quickstart, concepts, guides, API, and SDKs.',
    source: 'index.md',
  },
  {
    slug: 'quickstart',
    section: 'overview',
    title: 'Quickstart',
    summary:
      'Sign up, seed the default agency, run an agent, and inspect the trace — in five minutes.',
  },
  {
    slug: 'concepts/capability-class-routing',
    section: 'concepts',
    title: 'Capability-class routing',
    summary:
      'Agents declare capability classes; the gateway resolves a concrete model. Switching providers is a config change.',
  },
  {
    slug: 'concepts/privacy-tier',
    section: 'concepts',
    title: 'Privacy tier',
    summary:
      'A tier on every agent. `sensitive` is a hard gate: those runs physically cannot reach a cloud endpoint.',
  },
  {
    slug: 'concepts/multi-agent-orchestration',
    section: 'concepts',
    title: 'Multi-agent orchestration',
    summary:
      'Pipeline, supervisor, parallel, router, debate, and subscription strategies — declared in YAML, run by the engine.',
  },
  {
    slug: 'concepts/sandbox-and-guards',
    section: 'concepts',
    title: 'Sandbox and guards',
    summary:
      'Per-agent sandbox policy (network, filesystem) and tool-output guards (spotlighting, output scanner, quarantine).',
  },
  {
    slug: 'concepts/eval-harness',
    section: 'concepts',
    title: 'Eval harness',
    summary: 'Suites, sweeps, evaluators, datasets — the engine for promotion gating.',
  },
  {
    slug: 'concepts/replayability',
    section: 'concepts',
    title: 'Replayability',
    summary:
      'Every node boundary is a checkpoint. Edit-and-resume any step against a different model.',
  },
  {
    slug: 'concepts/iterative-loop',
    section: 'concepts',
    title: 'Iterative agent loop',
    summary:
      'Agents that loop until done — declarative termination conditions, parallel tool dispatch, history compression. The single canonical primitive for tool-using agents.',
  },
  {
    slug: 'concepts/approval-gates',
    section: 'concepts',
    title: 'Approval gates',
    summary:
      'Per-tool spec config that suspends the loop on destructive boundaries until a human approves. Fail-closed: misconfigured approvals never silently dispatch.',
  },
  {
    slug: 'concepts/agency',
    section: 'concepts',
    title: 'Reference agency',
    summary:
      'The reference organization shipped with ALDO AI. Use it as the example for every platform feature.',
  },
  {
    slug: 'guides/building-an-agent',
    section: 'guides',
    title: 'Building an agent',
    summary: 'From a blank YAML file to a promoted, eval-gated agent in your tenant.',
  },
  {
    slug: 'guides/writing-an-eval-suite',
    section: 'guides',
    title: 'Writing an eval suite',
    summary: 'Cases, evaluators, thresholds — the structure of a regression suite.',
  },
  {
    slug: 'guides/custom-evaluators',
    section: 'guides',
    title: 'Custom evaluators',
    summary: 'Ship your own evaluator: signature, lifecycle, sandboxing.',
  },
  {
    slug: 'guides/dataset-uploads',
    section: 'guides',
    title: 'Dataset uploads',
    summary: 'Upload JSONL or CSV; bind to suites; share across agents.',
  },
  {
    slug: 'guides/dashboards-and-alerts',
    section: 'guides',
    title: 'Dashboards and alerts',
    summary: 'Build a dashboard, configure an alert rule, route to integrations.',
  },
  {
    slug: 'guides/integrations',
    section: 'guides',
    title: 'Integrations',
    summary:
      'Slack, Discord, GitHub, webhooks, Telegram, email — secrets-encrypted at rest. Includes the approval-from-anywhere story (subscribe a Telegram bot to `approval_requested` and approve from your phone).',
  },
  {
    slug: 'guides/engagements',
    section: 'guides',
    title: 'Customer engagements',
    summary:
      'The engagement-shaped surface threads lacked: status, milestones with sign-off + reject, change-request comments, architectural-decision pins. Wire surface for unsupervised multi-day agency engagements.',
  },
  {
    slug: 'guides/budget-caps',
    section: 'guides',
    title: 'Spend caps',
    summary:
      'Per-run caps bound a single iterative loop; tenant-level engagement caps bound an entire multi-day run. Hard caps return HTTP 402; soft caps fire `budget_threshold` and let the run continue.',
  },
  {
    slug: 'guides/hybrid-cli',
    section: 'guides',
    title: 'Hybrid CLI (`aldo run --route`)',
    summary:
      'Local-only agents stay local; cloud-tier agents delegate to ai.aldo.tech. `--route auto` (default) decides; `--route local` and `--route hosted` override. The agency primitive reachable from a laptop.',
  },
  {
    slug: 'guides/api-keys',
    section: 'guides',
    title: 'API keys',
    summary: 'Mint scoped API keys; rotate; revoke; audit.',
  },
  {
    slug: 'guides/self-hosting',
    section: 'guides',
    title: 'Self-hosting',
    summary: 'Run ALDO AI on your own infra. Postgres, Redis, the gateway, the API.',
  },
  {
    slug: 'guides/local-models-mlx',
    section: 'guides',
    title: 'Local models — MLX (Apple Silicon)',
    summary: 'Run frontier-quality reasoning on your laptop without leaving the box.',
  },
  {
    slug: 'guides/mcp-server',
    section: 'guides',
    title: 'MCP server',
    summary:
      'Drive ALDO AI from Claude Desktop, Cursor, Claude Code, or any MCP-compatible client.',
  },
  {
    slug: 'guides/aldo-code',
    section: 'guides',
    title: 'aldo code (interactive coding TUI)',
    summary:
      "The platform's terminal coding companion. Streamed conversation, inline tool tiles, modal approval prompts, slash commands, and cross-session resume — built on `IterativeAgentRun`.",
  },
  {
    slug: 'sdks/python',
    section: 'sdks',
    title: 'Python SDK',
    summary: 'The official Python client for the ALDO AI control plane.',
  },
  {
    slug: 'sdks/typescript',
    section: 'sdks',
    title: 'TypeScript SDK',
    summary: '`@aldo-ai/sdk` — typed client for Node, browsers, Cloudflare Workers, Bun, Deno.',
  },
  {
    slug: 'changelog',
    section: 'reference',
    title: 'Changelog',
    summary: 'Release history — newest first.',
  },
  {
    slug: 'license',
    section: 'reference',
    title: 'License',
    summary: 'Functional Source License 1.1 with Apache 2.0 future license.',
  },
];

/**
 * Resolve the on-disk path (relative to apps/web/content/docs) for a
 * given page. Generated pages live under `api/_generated/<slug>.md`.
 */
export function pageSourcePath(page: DocPage): string {
  if (page.source) return page.source;
  return `${page.slug}.md`;
}

/**
 * Build the union of static + generated pages. The generator script
 * writes `api/_generated/<endpoint>.json`; pages are listed via
 * `loadGeneratedApiPages()` at request time so adding new endpoints
 * doesn't require rebuilding the registry.
 */
export interface GeneratedApiPage extends DocPage {
  readonly section: 'api';
  readonly generated: true;
}
